server:
  port: 8083

spring:
  application:
    name: membership-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library_db}
    #url: ${DB_URL:jdbc:postgresql://library-postgres:5432/library_db}
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    #bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:library-kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}

cashfree:
  app-id:     ${CASHFREE_APP_ID:}
  secret-key: ${CASHFREE_SECRET_KEY:}
  env:        ${CASHFREE_ENV:sandbox}

app:
  payment-gateway: ${PAYMENT_GATEWAY:CASHFREE}
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8082}