apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library-system
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_URL: "jdbc:postgresql://postgres-service:5432/library_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-service:8082"
  MEMBERSHIP_SERVICE_URL: "http://membership-service:8083"
  SEAT_SERVICE_URL: "http://seat-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
  ADMIN_SERVICE_URL: "http://admin-service:8086"
  FROM_EMAIL: "noreply@targetzone.co.in"
  FROM_NAME: "Target Zone Library"
  ADMIN_EMAIL: "admin@targetzone.co.in"
  UPLOAD_DIR: "/app/uploads"